import Head from "next/head";
import CounterArea from "components/Home/CounterArea";
import CategoryArea from "components/Home/CategoryArea";
import Header from "components/Home/Header";
import HeroArea from "components/Home/HeroArea";
import ResearchArea from "components/Home/ResearchArea";
import Footer from "components/common/Footer";
import Faq from "components/Home/Faq";
import BrandArea from "components/Home/BrandArea";
import CourseArea from "../components/Home/CourseArea";
import TeamArea from "../components/Home/TeamArea";

export default function Home() {
    return (
        <>
            <Head>
                <title>Mentor Mentee Connect</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>
            <HeroArea/>
            <CounterArea/>
            {/* <Features /> */}
            <CategoryArea/>
            <CourseArea/>
            <TeamArea/>
            {/* <AboutArea /> */}
            {/* <HomeCourses /> */}
            {/*<Events/>*/}
            {/*<Campus/>*/}

            <ResearchArea/>
            {/* <HomeBlog /> */}
            {/* <Cta /> */}
            <BrandArea/>
            <Faq/>
            <Footer/>
        </>
    );
}
